const PAPER_URL = "https://arxiv.org/abs/2502.01143";
const PROJECT_URL = "https://agile.human2humanoid.com/";
const CODE_URL = "https://github.com/LeCAR-Lab/ASAP";

window.ASAP_DECK = {
  title: "ASAP: Aligning Simulation and Real-World Physics",
  subtitle: "A compact lab presentation deck on agile humanoid whole-body transfer",
  sections: [
    {
      key: "setup",
      label: "1 Setup",
      chapters: ["Thesis", "Map", "Contribution"],
    },
    {
      key: "gap",
      label: "2 Transfer Gap",
      chapters: ["Why It Fails", "Baselines", "Positioning"],
    },
    {
      key: "pretrain",
      label: "3 Pre-training",
      chapters: ["Motion Source", "Tracking Policy", "Boundary"],
    },
    {
      key: "delta",
      label: "4 Alignment",
      chapters: ["Real Data", "Delta Action", "Fine-tuning", "Interpretation"],
    },
    {
      key: "evidence",
      label: "5 Evidence",
      chapters: ["Benchmarks", "Real Robot", "Ablations"],
    },
    {
      key: "synthesis",
      label: "6 Takeaways",
      chapters: ["Summary", "Limits", "Resources"],
    },
  ],
  slides: [
    {
      section: "setup",
      chapter: "Thesis",
      role: "Thesis",
      title: "ASAP",
      subtitle: "Aligning simulation and real-world physics for agile humanoid whole-body skills",
      lead: "ASAP targets a specific transfer failure: a motion-tracking policy looks strong in simulation, then breaks on hardware because the robot's effective physics differs from the simulator.",
      points: [
        "<strong>Problem.</strong> Agile whole-body motions are sensitive to contact timing, actuator limits, and hidden compliance.",
        "<strong>Core move.</strong> Learn a delta action model from real rollouts, insert it into simulation, and fine-tune the policy there.",
        "<strong>Deployment.</strong> The robot runs the fine-tuned policy only; the delta model is a training-time adapter.",
      ],
      visual: {
        type: "image",
        src: "assets/g1_motion.gif",
        alt: "Unitree G1 whole-body motion tracking",
        caption: "ASAP targets dynamic Unitree G1 whole-body motion tracking.",
        source: PROJECT_URL,
        sourceLabel: "project",
      },
    },
    {
      section: "setup",
      chapter: "Thesis",
      role: "Problem",
      title: "The bottleneck is physics transfer, not motion generation",
      subtitle: "Rich references already exist; keeping them stable on hardware is the hard part.",
      points: [
        "Human video, body reconstruction, and imitation learning already provide expressive target motions.",
        "The fragile step is <strong>closed-loop execution</strong> under real actuator, contact, and linkage effects.",
        "ASAP reframes the question from “how do we generate motion?” to “how do we train under more truthful dynamics?”",
      ],
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Reference motion", "Expressive human motion is already available through reconstruction and retargeting."],
          ["Tracking policy", "Simulation can train a strong feedback controller for that reference."],
          ["Transfer failure", "Hardware mismatch turns a locally good controller into a globally unstable one."],
        ],
      },
    },
    {
      section: "setup",
      chapter: "Map",
      role: "Map",
      title: "Compact map of the paper",
      subtitle: "The story is easiest to follow if everything stays tied to the policy-transfer loop.",
      visual: {
        type: "pipeline",
        steps: [
          ["Problem framing", "Why agile humanoid transfer fails and which alternatives ASAP competes with."],
          ["Pre-training", "Human motion becomes a simulator policy through retargeting and tracking RL."],
          ["Alignment", "Real rollouts teach a delta action model that reshapes the simulator."],
          ["Fine-tuning", "RL continues inside the aligned simulator, not directly on hardware."],
          ["Evidence", "The method is tested in simulator transfer, real robot transfer, and ablations."],
        ],
      },
    },
    {
      section: "setup",
      chapter: "Map",
      role: "Lens",
      title: "This deck keeps one question per slide",
      subtitle: "The goal is not to restate every definition, but to make the paper's logic easy to trace end-to-end.",
      visual: {
        type: "compare",
        rows: [
          ["Input", "Where does the motion come from?", "Human video is reconstructed, cleaned, and retargeted before RL begins."],
          ["Controller", "What is learned before real data?", "A phase-conditioned tracking policy is pretrained in simulation."],
          ["Alignment", "What changes after real rollouts?", "A delta action model reshapes simulated transitions before fine-tuning."],
          ["Evidence", "What proves the claim?", "The paper links dynamics matching, transfer gains, and real-robot behavior."],
        ],
      },
    },
    {
      section: "setup",
      chapter: "Contribution",
      role: "Contribution",
      title: "ASAP makes a narrow but important claim",
      subtitle: "It does not redesign the robot; it improves how a strong simulator policy is adapted to hardware.",
      points: [
        "The residual is <strong>learned from real rollouts</strong>, not hand-designed from parameter guesses.",
        "The correction acts during <strong>training</strong>, so deployment stays operationally simple.",
        "The paper validates the loop across simulator transfer and real Unitree G1 transfer.",
      ],
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Real-data residual", "The alignment signal comes from measured real transitions of the pretrained policy."],
          ["Aligned simulator", "The delta model is frozen into the simulator so RL can keep optimizing there."],
          ["Agile validation", "The method is tested on dynamic whole-body motions rather than only robust locomotion."],
        ],
      },
    },

    {
      section: "gap",
      chapter: "Why It Fails",
      role: "Context",
      title: "Agile whole-body skills are where mismatch shows up first",
      subtitle: "These motions compress many failure modes into short windows.",
      points: [
        "Impacts, aerial phases, and single-leg support leave little room for timing error.",
        "Actuator saturation and hidden compliance are amplified when motion changes quickly.",
        "A small mismatch can erase the landing, not just slightly reduce visual quality.",
      ],
      visual: {
        type: "terms",
        cols: 2,
        items: [
          ["Impact timing", "Contact events arrive on the wrong frame and the policy reacts too late."],
          ["Compliance", "Linkage elasticity and foot behavior differ from rigid-body assumptions."],
          ["Actuator gap", "Real motors can be weaker, slower, or more delayed than simulation expects."],
          ["Balance margin", "Dynamic motions leave less slack for cumulative state error."],
        ],
      },
    },
    {
      section: "gap",
      chapter: "Why It Fails",
      role: "Definition",
      title: "Transfer breaks when the transition function changes",
      subtitle: "The policy is evaluated under dynamics that are close enough to train, but not close enough to trust.",
      visual: {
        type: "formula",
        items: [
          ["Simulator", "s<sub>t+1</sub><sup>sim</sup> = f<sup>sim</sup>(s<sub>t</sub>, a<sub>t</sub>)"],
          ["Reality", "s<sub>t+1</sub><sup>real</sup> = f<sup>real</sup>(s<sub>t</sub>, a<sub>t</sub>)"],
          ["Symptom", "π trained under f<sup>sim</sup> can drift or fail under f<sup>real</sup>"],
        ],
      },
      points: [
        "The issue is not only state estimation noise; it is a changed <strong>closed-loop transition map</strong>.",
        "Once the state sequence diverges, the policy reaches parts of the motion it was never trained to recover from.",
      ],
    },
    {
      section: "gap",
      chapter: "Why It Fails",
      role: "Goal",
      title: "ASAP changes the training physics, not the deployed controller",
      subtitle: "The method aims to expose the policy to more realistic failure modes before deployment.",
      points: [
        "Collect real rollouts from the pretrained policy.",
        "Learn a delta action that makes replayed simulation look more like those rollouts.",
        "Fine-tune the policy inside that aligned simulator, then deploy the policy alone.",
      ],
      visual: {
        type: "pipeline",
        steps: [
          ["Pretrained policy", "Start from a controller that already tracks the motion well in simulation."],
          ["Real rollout data", "Observe how the same controller actually behaves on the robot."],
          ["Delta action learning", "Train an action correction model from paired sim-real transitions."],
          ["Aligned RL fine-tuning", "Continue policy optimization under the corrected simulator."],
        ],
      },
    },
    {
      section: "gap",
      chapter: "Baselines",
      role: "Comparison",
      title: "Common fixes leave different gaps",
      subtitle: "ASAP is best understood as a response to what other transfer strategies still miss.",
      visual: {
        type: "compare",
        rows: [
          ["System ID", "Tune simulator parameters", "Useful when the mismatch is global and identifiable, but brittle for local configuration-dependent effects."],
          ["Domain randomization", "Sample many plausible simulators", "Improves robustness, but does not target the actual bias seen on hardware."],
          ["State residuals", "Correct predicted next states", "Can match trajectories, but weakens the policy's control-side interpretation."],
          ["ASAP", "Correct effective actions", "Keeps the control interface intact while learning from measured transition error."],
        ],
      },
    },
    {
      section: "gap",
      chapter: "Baselines",
      role: "Choice",
      title: "Why action-space correction is a practical choice",
      subtitle: "It captures hidden physics through the control interface the policy already uses.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Local expressiveness", "A small action correction can absorb contact, latency, and linkage effects that only appear in certain states."],
          ["Clean policy interface", "The main policy still reasons in the same action space rather than learning around a new target state model."],
          ["Training compatibility", "The corrected simulator remains compatible with standard RL fine-tuning."],
        ],
      },
    },
    {
      section: "gap",
      chapter: "Positioning",
      role: "Positioning",
      title: "The claim is about transfer robustness under agile references",
      subtitle: "The key question is not how rich the simulated motion looks, but how much richness survives deployment.",
      visual: {
        type: "axis",
        xLeft: "robust locomotion",
        xRight: "expressive whole-body",
        yTop: "real deployment",
        yBottom: "simulation-only fidelity",
        points: [
          ["DeepMimic / AMP", 72, 72, "green"],
          ["Humanoid Parkour", 36, 27, "blue"],
          ["HumanPlus", 66, 33, "gold"],
          ["ASAP", 82, 26, "red"],
        ],
      },
      points: [
        "ASAP is strongest where motions are expressive enough to expose mismatch but structured enough to fine-tune through RL.",
      ],
    },
    {
      section: "gap",
      chapter: "Positioning",
      role: "Evaluation",
      title: "The paper is really answering three linked questions",
      subtitle: "Each experiment should support a different layer of the argument.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Can it match dynamics better?", "Replay tests ask whether corrected simulation is closer to measured real transitions."],
          ["Does RL benefit from that change?", "Closed-loop transfer tests ask whether the aligned simulator produces a stronger controller."],
          ["Does it matter on hardware?", "Real-robot tests ask whether more agility survives actual deployment."],
        ],
      },
    },

    {
      section: "pretrain",
      chapter: "Motion Source",
      role: "Input",
      title: "Stage 1 starts from human motion, not robot trajectories",
      subtitle: "The reference behavior is constructed before the robot policy is trained.",
      visual: {
        type: "pipeline",
        steps: [
          ["Human video", "Collect expressive motions from human demonstrations."],
          ["Body reconstruction", "Recover a body representation such as SMPL over time."],
          ["Cleaning", "Stabilize and repair trajectories so they become physically trainable."],
          ["Retargeting", "Map the motion to the Unitree G1 morphology and joints."],
        ],
      },
      points: [
        "ASAP inherits the usual motion-imitation stack rather than replacing it.",
        "Its novelty starts after a strong reference and tracking policy already exist.",
      ],
    },
    {
      section: "pretrain",
      chapter: "Motion Source",
      role: "Preparation",
      title: "Cleanup and retargeting make the motion trainable",
      subtitle: "Before RL, the reference must respect robot shape, contact feasibility, and joint structure.",
      points: [
        "Body reconstruction is expressive but not automatically robot-feasible.",
        "Shape fitting aligns human proportions with the target robot's geometry.",
        "Retargeting turns a body motion into a controller-ready reference trajectory.",
      ],
      visual: {
        type: "image",
        src: "assets/g1_shape.png",
        alt: "Unitree G1 shape fitting and retargeting",
        caption: "Reference preparation includes shape fitting and robot-specific retargeting.",
        source: PAPER_URL,
        sourceLabel: "paper",
      },
    },
    {
      section: "pretrain",
      chapter: "Tracking Policy",
      role: "Definition",
      title: "The tracking policy is phase-conditioned and proprioceptive",
      subtitle: "It is a feedback controller, not an animation player.",
      visual: {
        type: "terms",
        cols: 2,
        items: [
          ["Observations", "Joint state, base state, and phase-related information describe where the robot is now."],
          ["Phase", "A timing variable tells the policy where it should be within the motion cycle."],
          ["Action", "The policy outputs robot control commands, later interpreted through lower-level control."],
          ["Critic privilege", "Training can use richer simulator information than deployment, while the actor stays deployment-feasible."],
        ],
      },
    },
    {
      section: "pretrain",
      chapter: "Tracking Policy",
      role: "Mechanism",
      title: "Phase matters because the same pose can mean different intentions",
      subtitle: "Without timing, the policy cannot distinguish 'prepare to land' from 'recover after landing.'",
      visual: {
        type: "sequence",
        items: [
          ["Current state", "The robot may revisit a similar pose multiple times within one motion."],
          ["Phase-conditioned target", "The phase tells the controller which local objective matches that pose."],
          ["Corrective action", "The policy can then choose a context-appropriate correction instead of averaging behaviors."],
        ],
      },
      points: [
        "This is especially important for motions with symmetric poses but asymmetric future consequences.",
      ],
    },
    {
      section: "pretrain",
      chapter: "Tracking Policy",
      role: "Objective",
      title: "Pretraining reward mixes tracking quality with physical stability",
      subtitle: "The reward is shaped to keep the motion recognizable and the robot controllable.",
      visual: {
        type: "cards",
        cols: 2,
        items: [
          ["Pose tracking", "Match body pose and joint configuration to the reference motion."],
          ["Velocity / root terms", "Track base motion and temporal evolution, not only static poses."],
          ["Contact / limb behavior", "Encourage feet and end-effectors to follow the intended interaction pattern."],
          ["Regularization", "Keep actions and dynamics within stable operating regimes during learning."],
        ],
      },
    },
    {
      section: "pretrain",
      chapter: "Tracking Policy",
      role: "Output",
      title: "Stage 1 produces a strong simulator policy",
      subtitle: "The pretrained controller already tracks dynamic references convincingly inside simulation.",
      points: [
        "This stage is necessary: without a good base controller, real rollouts would not be informative enough.",
        "The paper's second stage improves transfer from this already-competent starting point.",
      ],
      visual: {
        type: "image",
        src: "assets/motion_tracking.gif",
        alt: "Simulation-based motion tracking",
        caption: "Pretraining produces a simulator policy that can already track dynamic references.",
        source: PROJECT_URL,
        sourceLabel: "project",
      },
    },
    {
      section: "pretrain",
      chapter: "Boundary",
      role: "Boundary",
      title: "Pretraining alone cannot identify hardware mismatch",
      subtitle: "Good simulator tracking says little about which real effects the controller is silently missing.",
      visual: {
        type: "compare",
        rows: [
          ["What stage 1 learns", "Reference-following control", "It learns how to behave under the simulator's transition function."],
          ["What stage 1 misses", "Real hidden dynamics", "It does not observe the hardware-specific bias that distorts those transitions."],
          ["Why stage 2 exists", "Physics alignment", "Real rollouts reveal the gap that simulator-only training cannot expose."],
        ],
      },
    },
    {
      section: "pretrain",
      chapter: "Boundary",
      role: "Transition",
      title: "Stage 2 begins exactly where stage 1 stops",
      subtitle: "Once the controller is competent, real rollouts become useful supervision about the missing physics.",
      visual: {
        type: "pipeline",
        steps: [
          ["Pretrain policy", "Learn a strong motion tracker in simulation."],
          ["Collect hardware rollouts", "Run that controller on the robot under safety limits."],
          ["Learn alignment", "Use the resulting transitions to fit the delta action model."],
        ],
      },
    },

    {
      section: "delta",
      chapter: "Real Data",
      role: "Data",
      title: "Real rollouts are the bridge to the missing physics",
      subtitle: "ASAP does not guess the gap; it measures it from the behavior of the pretrained controller on hardware.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Trajectory pairs", "The dataset contains states, actions, and next states from actual robot execution."],
          ["Safety-limited coverage", "Real data is valuable but scarce, so each rollout should reveal informative mismatch."],
          ["Replay-ready format", "The same state-action pairs can later be replayed in simulation for comparison."],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Real Data",
      role: "Mechanism",
      title: "Replay creates paired sim-real transitions",
      subtitle: "The same state and action are evaluated in both worlds, so the disagreement becomes a training target.",
      visual: {
        type: "formula",
        items: [
          ["Real record", "(s<sub>t</sub>, a<sub>t</sub>, s<sub>t+1</sub><sup>real</sup>)"],
          ["Sim replay", "f<sup>sim</sup>(s<sub>t</sub>, a<sub>t</sub>) → s<sub>t+1</sub><sup>sim</sup>"],
          ["Target gap", "s<sub>t+1</sub><sup>real</sup> - s<sub>t+1</sub><sup>sim</sup>"],
        ],
      },
      points: [
        "This is what turns limited hardware data into a reusable supervision signal for simulator alignment.",
      ],
    },
    {
      section: "delta",
      chapter: "Delta Action",
      role: "Definition",
      title: "The delta action model perturbs the simulator input",
      subtitle: "Its job is to make replayed simulation behave more like the robot.",
      visual: {
        type: "formula",
        items: [
          ["Base simulator", "s<sub>t+1</sub> = f<sup>sim</sup>(s<sub>t</sub>, a<sub>t</sub>)"],
          ["Corrected simulator", "s<sub>t+1</sub> = f<sup>sim</sup>(s<sub>t</sub>, a<sub>t</sub> + π<sup>Δ</sup>(s<sub>t</sub>, a<sub>t</sub>))"],
          ["Training target", "f<sup>sim</sup>(s<sub>t</sub>, a<sub>t</sub> + π<sup>Δ</sup>) ≈ s<sub>t+1</sub><sup>real</sup>"],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Delta Action",
      role: "Objective",
      title: "The learning target is transition alignment",
      subtitle: "The residual is trained to reduce one-step disagreement, not to imitate the main policy itself.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Input", "The delta model sees the current state and the action proposed by the main controller."],
          ["Output", "It predicts a corrective action that changes the simulator's effective command."],
          ["Loss", "The corrected simulator is optimized to land closer to the measured real next state."],
        ],
      },
      points: [
        "This keeps the learning problem localized: correct the transition first, then let RL re-solve the longer-horizon control problem.",
      ],
    },
    {
      section: "delta",
      chapter: "Delta Action",
      role: "Choice",
      title: "Why action residuals fit this paper's transfer problem",
      subtitle: "They absorb hidden actuator and linkage effects without demanding full model recovery.",
      visual: {
        type: "compare",
        rows: [
          ["Parameter tuning", "Interpretable simulator edits", "Useful, but difficult when the mismatch is local and state-dependent."],
          ["State residual", "Direct next-state correction", "Can match trajectories while weakening the policy's control-side meaning."],
          ["Action residual", "Control-side physics correction", "Captures hidden effects while preserving the policy's control interface."],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Fine-tuning",
      role: "Mechanism",
      title: "The aligned simulator is the real artifact that matters",
      subtitle: "Once the delta model is frozen, the simulator becomes a better teacher for policy improvement.",
      visual: {
        type: "pipeline",
        steps: [
          ["Collect data", "Run the pretrained controller on hardware."],
          ["Train delta", "Fit the residual so replayed simulation matches recorded reality."],
          ["Freeze delta", "Embed the learned correction into the simulator."],
          ["Fine-tune policy", "Run standard RL again under the aligned dynamics."],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Fine-tuning",
      role: "Procedure",
      title: "Fine-tuning is still reinforcement learning",
      subtitle: "ASAP does not replace RL; it changes the dynamics under which RL continues.",
      visual: {
        type: "sequence",
        items: [
          ["Initialize", "Start from the pretrained motion-tracking policy."],
          ["Roll out in aligned simulation", "Expose the controller to transitions that fail more like the robot."],
          ["Optimize return", "Keep the usual tracking objective while re-learning around the corrected dynamics."],
          ["Deploy updated policy", "Transfer the new controller to hardware without the delta model."],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Fine-tuning",
      role: "Deployment",
      title: "Deployment stays simple: only the policy runs on the robot",
      subtitle: "The delta model is a training-time adapter, not a runtime patch.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Operational simplicity", "The final controller remains a single policy, which keeps deployment manageable."],
          ["Safety clarity", "Runtime behavior does not depend on an extra learned correction module."],
          ["Training leverage", "The delta model matters because it improved the policy before deployment."],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Interpretation",
      role: "Example",
      title: "A small residual can encode structured hardware effects",
      subtitle: "The paper highlights ankle-related corrections because these joints are sensitive to hidden compliance and linkage mismatch.",
      points: [
        "The residual does not need to dominate every joint to matter.",
        "Localized corrections can propagate through contact events and improve whole-body stability.",
        "This is why an action-side representation can be effective even when the full model gap is complex.",
      ],
      visual: {
        type: "image",
        src: "assets/g1_shape.png",
        alt: "Unitree G1 morphology",
        caption: "Hardware-sensitive joints, especially near the ankle-contact chain, can benefit from structured residuals.",
        source: PAPER_URL,
        sourceLabel: "paper",
      },
    },
    {
      section: "delta",
      chapter: "Interpretation",
      role: "Interpretation",
      title: "The approximation only needs to be useful enough for policy improvement",
      subtitle: "ASAP does not require a perfect real-robot simulator to help.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Local faithfulness", "The corrected simulator should reproduce the failure modes the policy most needs to learn around."],
          ["RL recovery", "Fine-tuning can absorb remaining imperfections by re-optimizing the feedback controller."],
          ["Practical target", "Useful transfer improvement matters more than exact physical identification."],
        ],
      },
    },
    {
      section: "delta",
      chapter: "Interpretation",
      role: "Summary",
      title: "Method summary",
      subtitle: "ASAP is a two-stage loop with a learned physics adapter in the middle.",
      visual: {
        type: "pipeline",
        steps: [
          ["Reference motion", "Prepare human-derived motions that the humanoid should imitate."],
          ["Stage 1 pretraining", "Train a strong simulator policy for reference tracking."],
          ["Real rollout dataset", "Collect hardware transitions from that policy."],
          ["Delta action alignment", "Learn a correction that makes replayed simulation more realistic."],
          ["Stage 2 fine-tuning", "Re-optimize the policy in the aligned simulator, then deploy it."],
        ],
      },
    },

    {
      section: "evidence",
      chapter: "Benchmarks",
      role: "Setup",
      title: "The evaluation matrix separates three questions",
      subtitle: "ASAP is tested at the level of dynamics, policy transfer, and real-robot deployment.",
      visual: {
        type: "table",
        headers: ["Setting", "Question", "Why it matters"],
        rows: [
          ["Replay / dynamics matching", "Does the corrected simulator better match measured transitions?", "Checks whether the alignment signal itself is meaningful."],
          ["IsaacGym → IsaacSim / Genesis", "Does RL in the aligned simulator transfer better across dynamics?", "Separates method behavior from hardware-only confounds."],
          ["IsaacGym → real Unitree G1", "Does more agility survive real deployment?", "Tests the claim that matters operationally."],
          ["Ablations", "Which ingredients actually produce the gain?", "Prevents credit from being assigned to generic noise or extra training alone."],
        ],
      },
      layout: "wide",
    },
    {
      section: "evidence",
      chapter: "Benchmarks",
      role: "Evidence",
      title: "Dynamics matching improves before policy transfer does",
      subtitle: "The first sign that ASAP is helping is that replayed simulation stops disagreeing so strongly with reality.",
      visual: {
        type: "metrics",
        cols: 3,
        items: [
          ["Transition error", "↓", "Corrected simulation lands closer to the recorded next state."],
          ["Contact timing", "tighter", "The simulator reproduces foot-event timing more faithfully."],
          ["Control bias", "structured", "The learned correction captures hardware bias better than random perturbation."],
        ],
      },
      points: [
        "This matters because RL fine-tuning only helps if the simulator is first nudged in the right direction.",
      ],
    },
    {
      section: "evidence",
      chapter: "Benchmarks",
      role: "Evidence",
      title: "Closed-loop transfer improves next",
      subtitle: "Once the simulator is aligned, RL produces a controller that generalizes better across dynamics.",
      points: [
        "ASAP is not only a replay metric improvement; it changes the learned controller's behavior.",
        "Simulator-to-simulator tests are useful because they isolate transfer under controlled dynamics shifts.",
        "The gains are strongest on dynamic motions where mismatch accumulates quickly.",
      ],
      visual: {
        type: "image",
        src: "assets/sim2sim.gif",
        alt: "Simulator-to-simulator transfer result",
        caption: "Cross-simulator transfer is a clean test that the updated controller has learned more robust dynamics handling.",
        source: PROJECT_URL,
        sourceLabel: "project",
      },
    },
    {
      section: "evidence",
      chapter: "Benchmarks",
      role: "Evidence",
      title: "Hard motions are where the method earns its keep",
      subtitle: "Easy motions can hide transfer gaps; jumps, kicks, and dynamic balance expose them.",
      visual: {
        type: "compare",
        rows: [
          ["Easy tracking", "Small gap visible", "Many methods can look acceptable when the motion is slow and forgiving."],
          ["Dynamic balance", "Gap becomes obvious", "Timing and contact mismatch start to dominate controller behavior."],
          ["Explosive motions", "Gap becomes decisive", "A small mismatch can erase the entire skill instead of slightly degrading it."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Real Robot",
      role: "Constraint",
      title: "Real robot data is scarce, expensive, and safety-limited",
      subtitle: "That is why ASAP's data efficiency matters more than raw simulator elegance.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Collection cost", "Each rollout consumes robot time, operator attention, and safety margin."],
          ["Coverage limit", "The hardware dataset cannot simply brute-force every state the simulator can visit."],
          ["Design implication", "The method should reuse each rollout as a high-value alignment signal."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Real Robot",
      role: "Evidence",
      title: "Real-world results show the main point",
      subtitle: "Fine-tuning under aligned dynamics improves the policy that actually runs on the Unitree G1.",
      visual: {
        type: "table",
        headers: ["Question", "Pretraining only", "After ASAP fine-tuning"],
        rows: [
          ["Does the controller keep the motion?", "Often unstable on the hardest skills", "More of the reference motion remains executable."],
          ["Does transfer survive closed loop?", "Mismatch compounds and recovery weakens", "Recovery improves because training saw more realistic failure modes."],
          ["Does deployment stay simple?", "Yes", "Yes; the deployed artifact is still a single policy."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Real Robot",
      role: "Evidence",
      title: "The transfer gain matters most when mismatch compounds over time",
      subtitle: "ASAP is most useful when errors are not isolated, but snowball through contact and balance events.",
      points: [
        "This is why the method is better read through hard-motion transfer than through easy-motion average quality.",
        "The controller benefits when training encounters failure modes that resemble the robot's actual weak points.",
      ],
      visual: {
        type: "image",
        src: "assets/rviz.png",
        alt: "Real robot evaluation and visualization",
        caption: "Real-robot evaluation makes the transfer story concrete: the question is whether the skill still lives in closed loop.",
        source: PAPER_URL,
        sourceLabel: "paper",
      },
    },
    {
      section: "evidence",
      chapter: "Real Robot",
      role: "Demo",
      title: "Forward jump is the clean stress test",
      subtitle: "It is short, dynamic, and unforgiving: a small mismatch can ruin the landing immediately.",
      points: [
        "The motion exposes actuator, contact, and balance mismatch in a single sequence.",
        "This is the kind of skill where 'almost right' dynamics still fail in practice.",
      ],
      visual: {
        type: "image",
        src: "assets/motion_tracking.gif",
        alt: "Dynamic whole-body motion example",
        caption: "Dynamic reference tracking is useful only if the controller survives the landing and recovery phase.",
        source: PROJECT_URL,
        sourceLabel: "project",
      },
    },
    {
      section: "evidence",
      chapter: "Ablations",
      role: "Ablation",
      title: "More real data helps until coverage becomes repetitive",
      subtitle: "The delta model improves as the rollout set covers the states and motions that actually matter for transfer.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Too little data", "The residual sees only a narrow slice of the mismatch and overfits its usefulness."],
          ["Useful range", "Moderate rollout coverage already provides enough signal to improve transfer."],
          ["Diminishing returns", "Once the important failure modes are covered, repeated rollout types help less."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Ablations",
      role: "Ablation",
      title: "Horizon matters because errors compound",
      subtitle: "One-step correction is valuable only if it pushes the policy toward better future states.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Immediate match", "One-step alignment reduces local simulator bias."],
          ["Closed-loop effect", "The policy then re-optimizes around the corrected short-horizon physics."],
          ["Longer outcome", "Improved short steps matter because dynamic skills are a chain of error-sensitive events."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Ablations",
      role: "Ablation",
      title: "The delta model must be used in the right place",
      subtitle: "The gain comes from learning the residual and then fine-tuning with it, not from treating it as generic noise.",
      visual: {
        type: "compare",
        rows: [
          ["No delta", "Simulator stays biased", "Pretraining alone cannot learn around the missing physics."],
          ["Noise / generic perturbation", "Broadens training", "Does not reproduce the robot's structured bias."],
          ["Learned delta + fine-tuning", "Changes the training dynamics", "Lets RL adapt the full controller to a more truthful simulator."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Ablations",
      role: "Insight",
      title: "Joint-wise corrections are structured, not uniform",
      subtitle: "The learned residual concentrates where hidden compliance and actuation mismatch matter most.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Not all joints matter equally", "The residual should be strongest where the simulator is missing the most relevant effects."],
          ["Contact-chain sensitivity", "Errors near the support and landing chain can propagate into whole-body instability."],
          ["Interpretability hint", "Structured corrections suggest the model is learning physics bias, not random action jitter."],
        ],
      },
    },
    {
      section: "evidence",
      chapter: "Ablations",
      role: "Synthesis",
      title: "The evidence forms one coherent story",
      subtitle: "ASAP works because it aligns one-step dynamics first, then lets RL rebuild the controller around that change.",
      visual: {
        type: "pipeline",
        steps: [
          ["Real rollouts", "Measure hardware-specific transition bias."],
          ["Delta learning", "Encode that bias as an action-side correction."],
          ["Aligned fine-tuning", "Expose RL to more realistic failure modes."],
          ["Transfer gains", "Recover more agility in simulator transfer and on the robot."],
        ],
      },
    },

    {
      section: "synthesis",
      chapter: "Summary",
      role: "Takeaway",
      title: "What ASAP actually adds",
      subtitle: "It inserts a learned action-space adapter between pretraining and deployment.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Before ASAP", "A strong simulator controller still fails on unmodeled hardware effects."],
          ["With ASAP", "The simulator is nudged toward those effects before policy fine-tuning."],
          ["After ASAP", "The deployed controller keeps the same interface but carries more transfer-aware behavior."],
        ],
      },
    },
    {
      section: "synthesis",
      chapter: "Summary",
      role: "Guidance",
      title: "Use ASAP when the controller is already strong but transfer is brittle",
      subtitle: "The method is most valuable when simulator quality is decent, motions are dynamic, and some real rollout budget exists.",
      visual: {
        type: "terms",
        cols: 2,
        items: [
          ["Good fit", "A pretrained policy is strong in simulation but fragile on hardware."],
          ["Good fit", "The task contains dynamic contact or balance events that expose local mismatch."],
          ["Weak fit", "The simulator is fundamentally wrong across the entire task, not just biased in effective control."],
          ["Weak fit", "Real rollout coverage is too narrow to reveal the mismatch the policy actually faces."],
        ],
      },
    },
    {
      section: "synthesis",
      chapter: "Limits",
      role: "Limit",
      title: "ASAP is not a replacement for model quality or data coverage",
      subtitle: "If the simulator is deeply wrong or the rollout set is too narrow, the residual has little to stand on.",
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Coverage limit", "A delta learned from narrow data cannot fix failure modes it never sees."],
          ["Model limit", "Some mismatches may be too large to express as useful effective action corrections."],
          ["Task limit", "The method still depends on having a stable pretraining stage and a safe rollout pipeline."],
        ],
      },
    },
    {
      section: "synthesis",
      chapter: "Limits",
      role: "Next Step",
      title: "The strongest follow-up comparisons are about scale and refresh",
      subtitle: "The next question is how far this alignment idea can travel beyond one robot and one rollout pass.",
      visual: {
        type: "compare",
        rows: [
          ["Broader motion sets", "Test coverage scaling", "Does the same strategy hold when the reference library becomes much more diverse?"],
          ["Iterative real-data refresh", "Test online refinement", "How much better does the policy get if rollout collection and delta learning repeat?"],
          ["Other robots", "Test embodiment dependence", "How much of the gain depends on the specific Unitree G1 mismatch profile?"],
        ],
      },
    },
    {
      section: "synthesis",
      chapter: "Summary",
      role: "Conclusion",
      title: "Final takeaway",
      subtitle: "Train the policy under dynamics that fail like the real robot, and more agility survives deployment.",
      visual: {
        type: "quote",
        text: "ASAP matters because it shifts sim-to-real from generic robustness toward measured, task-relevant physics alignment.",
      },
    },
    {
      section: "synthesis",
      chapter: "Resources",
      role: "Resource",
      title: "Resources",
      subtitle: "Paper, project, code, and the deck's three questions in one place.",
      points: [
        `<strong>Paper.</strong> <a href="${PAPER_URL}" target="_blank" rel="noreferrer">${PAPER_URL}</a>`,
        `<strong>Project.</strong> <a href="${PROJECT_URL}" target="_blank" rel="noreferrer">${PROJECT_URL}</a>`,
        `<strong>Code.</strong> <a href="${CODE_URL}" target="_blank" rel="noreferrer">${CODE_URL}</a>`,
      ],
      visual: {
        type: "cards",
        cols: 3,
        items: [
          ["Question 1", "Can we measure the simulator's task-relevant physics gap from real rollouts?"],
          ["Question 2", "Can an action-side residual turn that signal into a better training simulator?"],
          ["Question 3", "Does fine-tuning in that simulator preserve more agile behavior on hardware?"],
        ],
      },
    },
  ],
};
